import { NgModule } from '@angular/core';
import {
  Bell,
  BellDot,
  Building2,
  ChevronRight,
  CircleAlert,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  FileText,
  FolderOpen,
  Globe2,
  History,
  LayoutDashboard,
  LoaderCircle,
  LogOut,
  LucideAngularModule,
  LucideIconProvider,
  LUCIDE_ICONS,
  MessageSquareQuote,
  MessagesSquare,
  PenTool,
  ReceiptText,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Sparkles,
  Upload,
  Users,
  WalletCards,
} from 'lucide-angular';

const SHELL_ICONS = {
  Bell,
  BellDot,
  Building2,
  ChevronRight,
  CircleAlert,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  FileText,
  FolderOpen,
  Globe2,
  History,
  LayoutDashboard,
  LoaderCircle,
  LogOut,
  MessageSquareQuote,
  MessagesSquare,
  PenTool,
  ReceiptText,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Sparkles,
  Upload,
  Users,
  WalletCards,
};

@NgModule({
  imports: [LucideAngularModule],
  exports: [LucideAngularModule],
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(SHELL_ICONS),
    },
  ],
})
export class LucideIconsModule {}
